#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kate
Version  : 24.12.0
Release  : 78
URL      : https://download.kde.org/stable/release-service/24.12.0/src/kate-24.12.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.0/src/kate-24.12.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.0/src/kate-24.12.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 LGPL-2.0 MIT
Requires: kate-bin = %{version}-%{release}
Requires: kate-data = %{version}-%{release}
Requires: kate-lib = %{version}-%{release}
Requires: kate-license = %{version}-%{release}
Requires: kate-locales = %{version}-%{release}
Requires: kate-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : ki18n-dev
BuildRequires : ktexteditor-dev
BuildRequires : qt6base-dev
BuildRequires : syntax-highlighting-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Kate XML plugin 0.9, 2002-07-20, Daniel Naber <daniel.naber@t-online.de>
This plugin gives hints about what's allowed at a certain position in
an XML file, according to the file's DTD. It will list possible
elements, attributes, attribute values or named entities, depending
on the cursor position. It's also possible to close the nearest
not-yet-closed element (this function's scope is limited to some
hundred characters).

%package bin
Summary: bin components for the kate package.
Group: Binaries
Requires: kate-data = %{version}-%{release}
Requires: kate-license = %{version}-%{release}

%description bin
bin components for the kate package.


%package data
Summary: data components for the kate package.
Group: Data

%description data
data components for the kate package.


%package doc
Summary: doc components for the kate package.
Group: Documentation
Requires: kate-man = %{version}-%{release}

%description doc
doc components for the kate package.


%package lib
Summary: lib components for the kate package.
Group: Libraries
Requires: kate-data = %{version}-%{release}
Requires: kate-license = %{version}-%{release}

%description lib
lib components for the kate package.


%package license
Summary: license components for the kate package.
Group: Default

%description license
license components for the kate package.


%package locales
Summary: locales components for the kate package.
Group: Default

%description locales
locales components for the kate package.


%package man
Summary: man components for the kate package.
Group: Default

%description man
man components for the kate package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kate-24.12.0
cd %{_builddir}/kate-24.12.0
pushd ..
cp -a kate-24.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735224058
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735224058
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kate
cp %{_builddir}/kate-%{version}/3rdparty/rbql/rbql-LICENSE %{buildroot}/usr/share/package-licenses/kate/5e2bdf2144559a2dd9c24785f35f2107c8cbbc30 || :
cp %{_builddir}/kate-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kate/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kate-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kate/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/kate-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kate/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kate-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kate/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kate-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kate/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kate
%find_lang katetextfilter
%find_lang katexmltools
%find_lang kate-ctags-plugin
%find_lang kate-replicode-plugin
%find_lang katebacktracebrowserplugin
%find_lang katebuild-plugin
%find_lang katecloseexceptplugin
%find_lang katecolorpickerplugin
%find_lang katefilebrowserplugin
%find_lang katefiletree
%find_lang kategdbplugin
%find_lang katekonsoleplugin
%find_lang kateproject
%find_lang katesearch
%find_lang katesnippetsplugin
%find_lang katesql
%find_lang katesymbolviewer
%find_lang katexmlcheck
%find_lang ktexteditorpreviewplugin
%find_lang tabswitcherplugin
%find_lang formatplugin
%find_lang kateexternaltoolsplugin
%find_lang kategitblameplugin
%find_lang katekeyboardmacros
%find_lang lspclient
%find_lang rainbowparens
%find_lang katecompilerexplorer
%find_lang rbqlplugin
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kate
/V3/usr/bin/kwrite
/usr/bin/kate
/usr/bin/kwrite

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kate.desktop
/usr/share/applications/org.kde.kwrite.desktop
/usr/share/icons/hicolor/128x128/apps/kate.png
/usr/share/icons/hicolor/128x128/apps/kwrite.png
/usr/share/icons/hicolor/150x150/apps/kate.png
/usr/share/icons/hicolor/150x150/apps/kwrite.png
/usr/share/icons/hicolor/16x16/apps/kate.png
/usr/share/icons/hicolor/16x16/apps/kwrite.png
/usr/share/icons/hicolor/22x22/apps/kate.png
/usr/share/icons/hicolor/22x22/apps/kwrite.png
/usr/share/icons/hicolor/256x256/apps/kate.png
/usr/share/icons/hicolor/256x256/apps/kwrite.png
/usr/share/icons/hicolor/310x310/apps/kate.png
/usr/share/icons/hicolor/310x310/apps/kwrite.png
/usr/share/icons/hicolor/32x32/apps/kate.png
/usr/share/icons/hicolor/32x32/apps/kwrite.png
/usr/share/icons/hicolor/44x44/apps/kate.png
/usr/share/icons/hicolor/44x44/apps/kwrite.png
/usr/share/icons/hicolor/48x48/apps/kate.png
/usr/share/icons/hicolor/48x48/apps/kwrite.png
/usr/share/icons/hicolor/512x512/apps/kate.png
/usr/share/icons/hicolor/512x512/apps/kwrite.png
/usr/share/icons/hicolor/64x64/apps/kate.png
/usr/share/icons/hicolor/64x64/apps/kwrite.png
/usr/share/icons/hicolor/scalable/apps/kate.svg
/usr/share/icons/hicolor/scalable/apps/kwrite.svg
/usr/share/kateproject/kateproject.example
/usr/share/katexmltools/html4-loose.dtd.xml
/usr/share/katexmltools/html4-strict.dtd.xml
/usr/share/katexmltools/kcfg.dtd.xml
/usr/share/katexmltools/kde-docbook.dtd.xml
/usr/share/katexmltools/kpartgui.dtd.xml
/usr/share/katexmltools/language.dtd.xml
/usr/share/katexmltools/simplify_dtd.xsl
/usr/share/katexmltools/testcases.xml
/usr/share/katexmltools/xhtml1-frameset.dtd.xml
/usr/share/katexmltools/xhtml1-strict.dtd.xml
/usr/share/katexmltools/xhtml1-transitional.dtd.xml
/usr/share/katexmltools/xslt-1.0.dtd.xml
/usr/share/metainfo/org.kde.kate.appdata.xml
/usr/share/metainfo/org.kde.kwrite.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kate/backtrace-settings.png
/usr/share/doc/HTML/ca/kate/build-output.png
/usr/share/doc/HTML/ca/kate/close-except-like.png
/usr/share/doc/HTML/ca/kate/configdialog01.png
/usr/share/doc/HTML/ca/kate/configuring.docbook
/usr/share/doc/HTML/ca/kate/ctags-global-setting.png
/usr/share/doc/HTML/ca/kate/development.docbook
/usr/share/doc/HTML/ca/kate/fundamentals.docbook
/usr/share/doc/HTML/ca/kate/gdb-io.png
/usr/share/doc/HTML/ca/kate/gdb-output.png
/usr/share/doc/HTML/ca/kate/gdb-settings.png
/usr/share/doc/HTML/ca/kate/index.cache.bz2
/usr/share/doc/HTML/ca/kate/index.docbook
/usr/share/doc/HTML/ca/kate/kate.png
/usr/share/doc/HTML/ca/kate/menus.docbook
/usr/share/doc/HTML/ca/kate/plugins.docbook
/usr/share/doc/HTML/ca/kate/project-completition.png
/usr/share/doc/HTML/ca/kate/project-configure.png
/usr/share/doc/HTML/ca/kate/project-current-analysis.png
/usr/share/doc/HTML/ca/kate/project-quickopen.png
/usr/share/doc/HTML/ca/kate/project-search.png
/usr/share/doc/HTML/ca/kate/project-view.png
/usr/share/doc/HTML/ca/kate/snippets-form.png
/usr/share/doc/HTML/ca/kate/snippets-panel.png
/usr/share/doc/HTML/ca/kate/snippets-repository.png
/usr/share/doc/HTML/ca/kate/snippets-usage.png
/usr/share/doc/HTML/ca/kate/symbolviewer-settings.png
/usr/share/doc/HTML/ca/kate/textfilter.png
/usr/share/doc/HTML/ca/katepart/advanced.docbook
/usr/share/doc/HTML/ca/katepart/configuring.docbook
/usr/share/doc/HTML/ca/katepart/development.docbook
/usr/share/doc/HTML/ca/katepart/fundamentals.docbook
/usr/share/doc/HTML/ca/katepart/index.cache.bz2
/usr/share/doc/HTML/ca/katepart/index.docbook
/usr/share/doc/HTML/ca/katepart/menus.docbook
/usr/share/doc/HTML/ca/katepart/minimap.png
/usr/share/doc/HTML/ca/katepart/part.docbook
/usr/share/doc/HTML/ca/katepart/regular-expressions.docbook
/usr/share/doc/HTML/ca/katepart/vi.docbook
/usr/share/doc/HTML/ca/kwrite/index.cache.bz2
/usr/share/doc/HTML/ca/kwrite/index.docbook
/usr/share/doc/HTML/de/kate/configuring.docbook
/usr/share/doc/HTML/de/kate/development.docbook
/usr/share/doc/HTML/de/kate/fundamentals.docbook
/usr/share/doc/HTML/de/kate/index.cache.bz2
/usr/share/doc/HTML/de/kate/index.docbook
/usr/share/doc/HTML/de/kate/menus.docbook
/usr/share/doc/HTML/de/kate/plugins.docbook
/usr/share/doc/HTML/de/katepart/advanced.docbook
/usr/share/doc/HTML/de/katepart/configuring.docbook
/usr/share/doc/HTML/de/katepart/development.docbook
/usr/share/doc/HTML/de/katepart/fundamentals.docbook
/usr/share/doc/HTML/de/katepart/index.cache.bz2
/usr/share/doc/HTML/de/katepart/index.docbook
/usr/share/doc/HTML/de/katepart/menus.docbook
/usr/share/doc/HTML/de/katepart/part.docbook
/usr/share/doc/HTML/de/katepart/regular-expressions.docbook
/usr/share/doc/HTML/de/katepart/vi.docbook
/usr/share/doc/HTML/de/kwrite/index.cache.bz2
/usr/share/doc/HTML/de/kwrite/index.docbook
/usr/share/doc/HTML/en/kate/arrow-down-double-22.png
/usr/share/doc/HTML/en/kate/arrow-up-double-22.png
/usr/share/doc/HTML/en/kate/backtrace-settings.png
/usr/share/doc/HTML/en/kate/bookmarks-22.png
/usr/share/doc/HTML/en/kate/build-output.png
/usr/share/doc/HTML/en/kate/close-except-like.png
/usr/share/doc/HTML/en/kate/configdialog01.png
/usr/share/doc/HTML/en/kate/configure-22.png
/usr/share/doc/HTML/en/kate/configure-shortcuts-22.png
/usr/share/doc/HTML/en/kate/configuring.docbook
/usr/share/doc/HTML/en/kate/ctags-global-setting.png
/usr/share/doc/HTML/en/kate/ctags-session-setting.png
/usr/share/doc/HTML/en/kate/development.docbook
/usr/share/doc/HTML/en/kate/dialog-ok-22.png
/usr/share/doc/HTML/en/kate/document-new-22.png
/usr/share/doc/HTML/en/kate/document-open-22.png
/usr/share/doc/HTML/en/kate/document-save-22.png
/usr/share/doc/HTML/en/kate/document-save-as-22.png
/usr/share/doc/HTML/en/kate/documentswitcher.png
/usr/share/doc/HTML/en/kate/edit-copy-22.png
/usr/share/doc/HTML/en/kate/edit-delete-22.png
/usr/share/doc/HTML/en/kate/edit-select-all-22.png
/usr/share/doc/HTML/en/kate/format-text-superscript-22.png
/usr/share/doc/HTML/en/kate/fundamentals.docbook
/usr/share/doc/HTML/en/kate/games-config-options-22.png
/usr/share/doc/HTML/en/kate/gdb-call-stack.png
/usr/share/doc/HTML/en/kate/gdb-io.png
/usr/share/doc/HTML/en/kate/gdb-locals.png
/usr/share/doc/HTML/en/kate/gdb-output.png
/usr/share/doc/HTML/en/kate/gdb-settings.png
/usr/share/doc/HTML/en/kate/go-down-22.png
/usr/share/doc/HTML/en/kate/go-next-22.png
/usr/share/doc/HTML/en/kate/go-previous-22.png
/usr/share/doc/HTML/en/kate/go-up-22.png
/usr/share/doc/HTML/en/kate/index.cache.bz2
/usr/share/doc/HTML/en/kate/index.docbook
/usr/share/doc/HTML/en/kate/kate.png
/usr/share/doc/HTML/en/kate/kateeditexternaltool.png
/usr/share/doc/HTML/en/kate/kateexternaltools.png
/usr/share/doc/HTML/en/kate/kateexternaltoolvariablechooser.png
/usr/share/doc/HTML/en/kate/katevariableexpansion.png
/usr/share/doc/HTML/en/kate/list-add-22.png
/usr/share/doc/HTML/en/kate/mascot_kate.png
/usr/share/doc/HTML/en/kate/menus.docbook
/usr/share/doc/HTML/en/kate/plugins.docbook
/usr/share/doc/HTML/en/kate/project-completition.png
/usr/share/doc/HTML/en/kate/project-configure.png
/usr/share/doc/HTML/en/kate/project-current-analysis.png
/usr/share/doc/HTML/en/kate/project-quickopen.png
/usr/share/doc/HTML/en/kate/project-search.png
/usr/share/doc/HTML/en/kate/project-view.png
/usr/share/doc/HTML/en/kate/snippets-form.png
/usr/share/doc/HTML/en/kate/snippets-panel.png
/usr/share/doc/HTML/en/kate/snippets-repository.png
/usr/share/doc/HTML/en/kate/snippets-usage.png
/usr/share/doc/HTML/en/kate/symbolviewer-settings.png
/usr/share/doc/HTML/en/kate/system-switch-user-22.png
/usr/share/doc/HTML/en/kate/tab-duplicate-22.png
/usr/share/doc/HTML/en/kate/tab-new-22.png
/usr/share/doc/HTML/en/kate/textfilter.png
/usr/share/doc/HTML/en/kate/view-refresh-22.png
/usr/share/doc/HTML/en/kate/view-split-left-right-22.png
/usr/share/doc/HTML/en/katepart/advanced.docbook
/usr/share/doc/HTML/en/katepart/arrow-down-double-22.png
/usr/share/doc/HTML/en/katepart/arrow-up-double-22.png
/usr/share/doc/HTML/en/katepart/breeze-color-theme-preview.png
/usr/share/doc/HTML/en/katepart/color-themes-gui-breeze-dark-default-text-styles.png
/usr/share/doc/HTML/en/katepart/color-themes-gui-default-text-styles.png
/usr/share/doc/HTML/en/katepart/comma-to.png
/usr/share/doc/HTML/en/katepart/configure-shortcuts-22.png
/usr/share/doc/HTML/en/katepart/configuring.docbook
/usr/share/doc/HTML/en/katepart/development.docbook
/usr/share/doc/HTML/en/katepart/edit-select-all-22.png
/usr/share/doc/HTML/en/katepart/editor-colors-BackgroundColor.png
/usr/share/doc/HTML/en/katepart/editor-colors-BracketMatching.png
/usr/share/doc/HTML/en/katepart/editor-colors-CodeFolding.png
/usr/share/doc/HTML/en/katepart/editor-colors-CurrentLine.png
/usr/share/doc/HTML/en/katepart/editor-colors-IconBorder.png
/usr/share/doc/HTML/en/katepart/editor-colors-IndentationLine.png
/usr/share/doc/HTML/en/katepart/editor-colors-MarkBookmark.png
/usr/share/doc/HTML/en/katepart/editor-colors-ModifiedLines.png
/usr/share/doc/HTML/en/katepart/editor-colors-ReplaceHighlight.png
/usr/share/doc/HTML/en/katepart/editor-colors-SearchHighlight.png
/usr/share/doc/HTML/en/katepart/editor-colors-SpellChecking.png
/usr/share/doc/HTML/en/katepart/editor-colors-TabMarker.png
/usr/share/doc/HTML/en/katepart/editor-colors-Template.png
/usr/share/doc/HTML/en/katepart/editor-colors-TemplateAndSnippets.png
/usr/share/doc/HTML/en/katepart/editor-colors-TemplateReadOnlyPlaceholder.png
/usr/share/doc/HTML/en/katepart/editor-colors-TextSelection.png
/usr/share/doc/HTML/en/katepart/editor-colors-WordWrapMarker.png
/usr/share/doc/HTML/en/katepart/format-text-superscript-22.png
/usr/share/doc/HTML/en/katepart/fundamentals.docbook
/usr/share/doc/HTML/en/katepart/highlighted.png
/usr/share/doc/HTML/en/katepart/index.cache.bz2
/usr/share/doc/HTML/en/katepart/index.docbook
/usr/share/doc/HTML/en/katepart/kf5-ksyntaxhighlighting.png
/usr/share/doc/HTML/en/katepart/ksyntaxhighlighter6-trace-format.png
/usr/share/doc/HTML/en/katepart/line-modification-system.png
/usr/share/doc/HTML/en/katepart/menus.docbook
/usr/share/doc/HTML/en/katepart/minimap.png
/usr/share/doc/HTML/en/katepart/part.docbook
/usr/share/doc/HTML/en/katepart/regular-expressions.docbook
/usr/share/doc/HTML/en/katepart/unhighlighted.png
/usr/share/doc/HTML/en/katepart/vi.docbook
/usr/share/doc/HTML/en/kwrite/index.cache.bz2
/usr/share/doc/HTML/en/kwrite/index.docbook
/usr/share/doc/HTML/eo/kate/configuring.docbook
/usr/share/doc/HTML/eo/kate/development.docbook
/usr/share/doc/HTML/eo/kate/fundamentals.docbook
/usr/share/doc/HTML/eo/kate/index.cache.bz2
/usr/share/doc/HTML/eo/kate/index.docbook
/usr/share/doc/HTML/eo/kate/menus.docbook
/usr/share/doc/HTML/eo/kate/plugins.docbook
/usr/share/doc/HTML/eo/katepart/advanced.docbook
/usr/share/doc/HTML/eo/katepart/configuring.docbook
/usr/share/doc/HTML/eo/katepart/development.docbook
/usr/share/doc/HTML/eo/katepart/fundamentals.docbook
/usr/share/doc/HTML/eo/katepart/index.cache.bz2
/usr/share/doc/HTML/eo/katepart/index.docbook
/usr/share/doc/HTML/eo/katepart/menus.docbook
/usr/share/doc/HTML/eo/katepart/part.docbook
/usr/share/doc/HTML/eo/katepart/regular-expressions.docbook
/usr/share/doc/HTML/eo/katepart/vi.docbook
/usr/share/doc/HTML/eo/kwrite/index.cache.bz2
/usr/share/doc/HTML/eo/kwrite/index.docbook
/usr/share/doc/HTML/es/kwrite/index.cache.bz2
/usr/share/doc/HTML/es/kwrite/index.docbook
/usr/share/doc/HTML/it/kate/configuring.docbook
/usr/share/doc/HTML/it/kate/development.docbook
/usr/share/doc/HTML/it/kate/fundamentals.docbook
/usr/share/doc/HTML/it/kate/index.cache.bz2
/usr/share/doc/HTML/it/kate/index.docbook
/usr/share/doc/HTML/it/kate/menus.docbook
/usr/share/doc/HTML/it/kate/plugins.docbook
/usr/share/doc/HTML/it/katepart/advanced.docbook
/usr/share/doc/HTML/it/katepart/configuring.docbook
/usr/share/doc/HTML/it/katepart/development.docbook
/usr/share/doc/HTML/it/katepart/fundamentals.docbook
/usr/share/doc/HTML/it/katepart/index.cache.bz2
/usr/share/doc/HTML/it/katepart/index.docbook
/usr/share/doc/HTML/it/katepart/menus.docbook
/usr/share/doc/HTML/it/katepart/part.docbook
/usr/share/doc/HTML/it/katepart/regular-expressions.docbook
/usr/share/doc/HTML/it/katepart/vi.docbook
/usr/share/doc/HTML/it/kwrite/index.cache.bz2
/usr/share/doc/HTML/it/kwrite/index.docbook
/usr/share/doc/HTML/ko/kwrite/index.cache.bz2
/usr/share/doc/HTML/ko/kwrite/index.docbook
/usr/share/doc/HTML/nl/kate/configuring.docbook
/usr/share/doc/HTML/nl/kate/development.docbook
/usr/share/doc/HTML/nl/kate/fundamentals.docbook
/usr/share/doc/HTML/nl/kate/index.cache.bz2
/usr/share/doc/HTML/nl/kate/index.docbook
/usr/share/doc/HTML/nl/kate/menus.docbook
/usr/share/doc/HTML/nl/kate/plugins.docbook
/usr/share/doc/HTML/nl/katepart/advanced.docbook
/usr/share/doc/HTML/nl/katepart/configuring.docbook
/usr/share/doc/HTML/nl/katepart/development.docbook
/usr/share/doc/HTML/nl/katepart/fundamentals.docbook
/usr/share/doc/HTML/nl/katepart/index.cache.bz2
/usr/share/doc/HTML/nl/katepart/index.docbook
/usr/share/doc/HTML/nl/katepart/menus.docbook
/usr/share/doc/HTML/nl/katepart/part.docbook
/usr/share/doc/HTML/nl/katepart/regular-expressions.docbook
/usr/share/doc/HTML/nl/katepart/vi.docbook
/usr/share/doc/HTML/nl/kwrite/index.cache.bz2
/usr/share/doc/HTML/nl/kwrite/index.docbook
/usr/share/doc/HTML/pt/kwrite/index.cache.bz2
/usr/share/doc/HTML/pt/kwrite/index.docbook
/usr/share/doc/HTML/pt_BR/kate/comma-to.png
/usr/share/doc/HTML/pt_BR/kate/configdialog01.png
/usr/share/doc/HTML/pt_BR/kate/configuring.docbook
/usr/share/doc/HTML/pt_BR/kate/development.docbook
/usr/share/doc/HTML/pt_BR/kate/fundamentals.docbook
/usr/share/doc/HTML/pt_BR/kate/highlighted.png
/usr/share/doc/HTML/pt_BR/kate/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kate/index.docbook
/usr/share/doc/HTML/pt_BR/kate/mascot_kate.png
/usr/share/doc/HTML/pt_BR/kate/menus.docbook
/usr/share/doc/HTML/pt_BR/kate/plugins.docbook
/usr/share/doc/HTML/pt_BR/kate/unhighlighted.png
/usr/share/doc/HTML/pt_BR/katepart/advanced.docbook
/usr/share/doc/HTML/pt_BR/katepart/configuring.docbook
/usr/share/doc/HTML/pt_BR/katepart/development.docbook
/usr/share/doc/HTML/pt_BR/katepart/fundamentals.docbook
/usr/share/doc/HTML/pt_BR/katepart/index.cache.bz2
/usr/share/doc/HTML/pt_BR/katepart/index.docbook
/usr/share/doc/HTML/pt_BR/katepart/menus.docbook
/usr/share/doc/HTML/pt_BR/katepart/part.docbook
/usr/share/doc/HTML/pt_BR/katepart/regular-expressions.docbook
/usr/share/doc/HTML/pt_BR/katepart/vi.docbook
/usr/share/doc/HTML/pt_BR/kwrite/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kwrite/index.docbook
/usr/share/doc/HTML/ru/kate/configuring.docbook
/usr/share/doc/HTML/ru/kate/development.docbook
/usr/share/doc/HTML/ru/kate/fundamentals.docbook
/usr/share/doc/HTML/ru/kate/index.cache.bz2
/usr/share/doc/HTML/ru/kate/index.docbook
/usr/share/doc/HTML/ru/kate/menus.docbook
/usr/share/doc/HTML/ru/kate/plugins.docbook
/usr/share/doc/HTML/ru/katepart/advanced.docbook
/usr/share/doc/HTML/ru/katepart/configuring.docbook
/usr/share/doc/HTML/ru/katepart/development.docbook
/usr/share/doc/HTML/ru/katepart/fundamentals.docbook
/usr/share/doc/HTML/ru/katepart/index.cache.bz2
/usr/share/doc/HTML/ru/katepart/index.docbook
/usr/share/doc/HTML/ru/katepart/menus.docbook
/usr/share/doc/HTML/ru/katepart/part.docbook
/usr/share/doc/HTML/ru/katepart/regular-expressions.docbook
/usr/share/doc/HTML/ru/katepart/vi.docbook
/usr/share/doc/HTML/ru/kwrite/index.cache.bz2
/usr/share/doc/HTML/ru/kwrite/index.docbook
/usr/share/doc/HTML/sv/kate/configuring.docbook
/usr/share/doc/HTML/sv/kate/development.docbook
/usr/share/doc/HTML/sv/kate/fundamentals.docbook
/usr/share/doc/HTML/sv/kate/index.cache.bz2
/usr/share/doc/HTML/sv/kate/index.docbook
/usr/share/doc/HTML/sv/kate/menus.docbook
/usr/share/doc/HTML/sv/kate/plugins.docbook
/usr/share/doc/HTML/sv/katepart/advanced.docbook
/usr/share/doc/HTML/sv/katepart/configuring.docbook
/usr/share/doc/HTML/sv/katepart/development.docbook
/usr/share/doc/HTML/sv/katepart/fundamentals.docbook
/usr/share/doc/HTML/sv/katepart/index.cache.bz2
/usr/share/doc/HTML/sv/katepart/index.docbook
/usr/share/doc/HTML/sv/katepart/menus.docbook
/usr/share/doc/HTML/sv/katepart/part.docbook
/usr/share/doc/HTML/sv/katepart/regular-expressions.docbook
/usr/share/doc/HTML/sv/katepart/vi.docbook
/usr/share/doc/HTML/sv/kwrite/index.cache.bz2
/usr/share/doc/HTML/sv/kwrite/index.docbook
/usr/share/doc/HTML/tr/kate/configuring.docbook
/usr/share/doc/HTML/tr/kate/development.docbook
/usr/share/doc/HTML/tr/kate/fundamentals.docbook
/usr/share/doc/HTML/tr/kate/index.cache.bz2
/usr/share/doc/HTML/tr/kate/index.docbook
/usr/share/doc/HTML/tr/kate/menus.docbook
/usr/share/doc/HTML/tr/kate/plugins.docbook
/usr/share/doc/HTML/tr/katepart/advanced.docbook
/usr/share/doc/HTML/tr/katepart/configuring.docbook
/usr/share/doc/HTML/tr/katepart/development.docbook
/usr/share/doc/HTML/tr/katepart/fundamentals.docbook
/usr/share/doc/HTML/tr/katepart/index.cache.bz2
/usr/share/doc/HTML/tr/katepart/index.docbook
/usr/share/doc/HTML/tr/katepart/menus.docbook
/usr/share/doc/HTML/tr/katepart/part.docbook
/usr/share/doc/HTML/tr/katepart/regular-expressions.docbook
/usr/share/doc/HTML/tr/katepart/vi.docbook
/usr/share/doc/HTML/tr/kwrite/index.cache.bz2
/usr/share/doc/HTML/tr/kwrite/index.docbook
/usr/share/doc/HTML/uk/kate/backtrace-settings.png
/usr/share/doc/HTML/uk/kate/build-output.png
/usr/share/doc/HTML/uk/kate/close-except-like.png
/usr/share/doc/HTML/uk/kate/configdialog01.png
/usr/share/doc/HTML/uk/kate/configuring.docbook
/usr/share/doc/HTML/uk/kate/ctags-global-setting.png
/usr/share/doc/HTML/uk/kate/ctags-session-setting.png
/usr/share/doc/HTML/uk/kate/development.docbook
/usr/share/doc/HTML/uk/kate/fundamentals.docbook
/usr/share/doc/HTML/uk/kate/gdb-output.png
/usr/share/doc/HTML/uk/kate/gdb-settings.png
/usr/share/doc/HTML/uk/kate/index.cache.bz2
/usr/share/doc/HTML/uk/kate/index.docbook
/usr/share/doc/HTML/uk/kate/kate.png
/usr/share/doc/HTML/uk/kate/menus.docbook
/usr/share/doc/HTML/uk/kate/plugins.docbook
/usr/share/doc/HTML/uk/kate/project-completition.png
/usr/share/doc/HTML/uk/kate/project-configure.png
/usr/share/doc/HTML/uk/kate/project-current-analysis.png
/usr/share/doc/HTML/uk/kate/project-quickopen.png
/usr/share/doc/HTML/uk/kate/project-search.png
/usr/share/doc/HTML/uk/kate/project-view.png
/usr/share/doc/HTML/uk/kate/textfilter.png
/usr/share/doc/HTML/uk/katepart/advanced.docbook
/usr/share/doc/HTML/uk/katepart/configuring.docbook
/usr/share/doc/HTML/uk/katepart/development.docbook
/usr/share/doc/HTML/uk/katepart/editor-colors-BackgroundColor.png
/usr/share/doc/HTML/uk/katepart/editor-colors-BracketMatching.png
/usr/share/doc/HTML/uk/katepart/editor-colors-CurrentLine.png
/usr/share/doc/HTML/uk/katepart/editor-colors-IconBorder.png
/usr/share/doc/HTML/uk/katepart/editor-colors-MarkBookmark.png
/usr/share/doc/HTML/uk/katepart/editor-colors-SearchHighlight.png
/usr/share/doc/HTML/uk/katepart/editor-colors-SpellChecking.png
/usr/share/doc/HTML/uk/katepart/editor-colors-TabMarker.png
/usr/share/doc/HTML/uk/katepart/editor-colors-Template.png
/usr/share/doc/HTML/uk/katepart/editor-colors-TemplateAndSnippets.png
/usr/share/doc/HTML/uk/katepart/editor-colors-TemplateReadOnlyPlaceholder.png
/usr/share/doc/HTML/uk/katepart/editor-colors-TextSelection.png
/usr/share/doc/HTML/uk/katepart/fundamentals.docbook
/usr/share/doc/HTML/uk/katepart/index.cache.bz2
/usr/share/doc/HTML/uk/katepart/index.docbook
/usr/share/doc/HTML/uk/katepart/kf5-ksyntaxhighlighting.png
/usr/share/doc/HTML/uk/katepart/menus.docbook
/usr/share/doc/HTML/uk/katepart/minimap.png
/usr/share/doc/HTML/uk/katepart/part.docbook
/usr/share/doc/HTML/uk/katepart/regular-expressions.docbook
/usr/share/doc/HTML/uk/katepart/vi.docbook
/usr/share/doc/HTML/uk/kwrite/index.cache.bz2
/usr/share/doc/HTML/uk/kwrite/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkateprivate.so.24.12.0
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/cmaketoolsplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/compilerexplorer.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/eslintplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/externaltoolsplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/formatplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katebacktracebrowserplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katebuildplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katecloseexceptplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katecolorpickerplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katectagsplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katefilebrowserplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katefiletreeplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/kategdbplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/kategitblameplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katekonsoleplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/kateprojectplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katereplicodeplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katesearchplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katesnippetsplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katesymbolviewerplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katexmlcheckplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/katexmltoolsplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/keyboardmacrosplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/ktexteditorpreviewplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/latexcompletionplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/lspclientplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/openlinkplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/rainbowparens.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/rbqlplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/tabswitcherplugin.so
/V3/usr/lib64/qt6/plugins/kf6/ktexteditor/textfilterplugin.so
/usr/lib64/libkateprivate.so.24.12.0
/usr/lib64/qt6/plugins/kf6/ktexteditor/cmaketoolsplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/compilerexplorer.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/eslintplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/externaltoolsplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/formatplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katebacktracebrowserplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katebuildplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katecloseexceptplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katecolorpickerplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katectagsplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katefilebrowserplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katefiletreeplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/kategdbplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/kategitblameplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katekonsoleplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/kateprojectplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katereplicodeplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katesearchplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katesnippetsplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katesymbolviewerplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katexmlcheckplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/katexmltoolsplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/keyboardmacrosplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/ktexteditorpreviewplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/latexcompletionplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/lspclientplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/openlinkplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/rainbowparens.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/rbqlplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/tabswitcherplugin.so
/usr/lib64/qt6/plugins/kf6/ktexteditor/textfilterplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kate/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kate/5e2bdf2144559a2dd9c24785f35f2107c8cbbc30
/usr/share/package-licenses/kate/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kate/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kate/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/ca/man1/kate.1
/usr/share/man/de/man1/kate.1
/usr/share/man/eo/man1/kate.1
/usr/share/man/es/man1/kate.1
/usr/share/man/fr/man1/kate.1
/usr/share/man/it/man1/kate.1
/usr/share/man/man1/kate.1
/usr/share/man/nl/man1/kate.1
/usr/share/man/pt/man1/kate.1
/usr/share/man/pt_BR/man1/kate.1
/usr/share/man/ru/man1/kate.1
/usr/share/man/sv/man1/kate.1
/usr/share/man/tr/man1/kate.1
/usr/share/man/uk/man1/kate.1

%files locales -f kate.lang -f katetextfilter.lang -f katexmltools.lang -f kate-ctags-plugin.lang -f kate-replicode-plugin.lang -f katebacktracebrowserplugin.lang -f katebuild-plugin.lang -f katecloseexceptplugin.lang -f katecolorpickerplugin.lang -f katefilebrowserplugin.lang -f katefiletree.lang -f kategdbplugin.lang -f katekonsoleplugin.lang -f kateproject.lang -f katesearch.lang -f katesnippetsplugin.lang -f katesql.lang -f katesymbolviewer.lang -f katexmlcheck.lang -f ktexteditorpreviewplugin.lang -f tabswitcherplugin.lang -f formatplugin.lang -f kateexternaltoolsplugin.lang -f kategitblameplugin.lang -f katekeyboardmacros.lang -f lspclient.lang -f rainbowparens.lang -f katecompilerexplorer.lang -f rbqlplugin.lang
%defattr(-,root,root,-)

